# =============================================================
#  cursos-service (core) - CDY2204 EFT
# =============================================================
spring.application.name=cursos-service
server.port=8081

# -------------------------------------------------------------
#  Oracle Cloud (Autonomous Database) via Wallet mTLS
#  Local: wallet descomprimido en ./wallet ; EC2/Docker: /app/wallet
# -------------------------------------------------------------
spring.datasource.url=${ORACLE_JDBC_URL:jdbc:oracle:thin:@oraclecloudfparradb_tp?TNS_ADMIN=./wallet}
spring.datasource.username=${ORACLE_USER:ADMIN}
spring.datasource.password=${ORACLE_PASSWORD:}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.connection-timeout=30000

# -------------------------------------------------------------
#  Azure AD B2C (IDaaS)
# -------------------------------------------------------------
spring.security.oauth2.resourceserver.jwt.issuer-uri=${AZURE_ISSUER_URI:https://login.microsoftonline.com/REEMPLAZAR/v2.0}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${AZURE_JWKS_URI:https://REEMPLAZAR.b2clogin.com/REEMPLAZAR/discovery/v2.0/keys}
azure.b2c.audience=${AZURE_AUDIENCE:REEMPLAZAR_CLIENT_ID}
azure.b2c.role-claim=${AZURE_ROLE_CLAIM:extension_rol}

# -------------------------------------------------------------
#  AWS S3 (material de cursos)
# -------------------------------------------------------------
aws.s3.bucket-name=${AWS_S3_BUCKET:REEMPLAZAR_BUCKET_S3}
aws.s3.region=${AWS_S3_REGION:us-east-1}
aws.access-key=${AWS_ACCESS_KEY_ID:}
aws.secret-key=${AWS_SECRET_ACCESS_KEY:}
aws.session-token=${AWS_SESSION_TOKEN:}

# Swagger / Actuator / uploads
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never
spring.servlet.multipart.max-file-size=15MB
spring.servlet.multipart.max-request-size=15MB
